const KEY = "codeRealmPlayer";
const defaults = {name:"Aventurero",rank:"NOVATO",level:1,exp:0,crystals:0,gold:0,xpNext:100,act1Completed:0,act1Total:2,mission1Completed:false,mission2Completed:false,mission1Step:0,mission2Step:0};
const player = {...defaults,...(JSON.parse(localStorage.getItem(KEY)||"{}")||{})};
const $ = s => document.querySelector(s);
const missions = [
 {id:1,title:"La llamada del código",desc:"Conoce cómo aprenderás en CODE REALM y descubre tus primeras ideas sobre programación y HTML.",reward:"+50 EXP",file:"act1.html",completedKey:"mission1Completed"},
 {id:2,title:"Consigue tu herramienta",desc:"Instala Visual Studio Code, crea tu primera carpeta y prepara tu taller real de programación.",reward:"+100 EXP",file:"act2.html",completedKey:"mission2Completed"}
];
function save(){localStorage.setItem(KEY,JSON.stringify(player));}
function updateHud(){const xp=Number(player.exp||0), next=Number(player.xpNext||100), pct=Math.min(100,xp/next*100), n=player.name||"Aventurero"; $("#playerName").textContent=n.toUpperCase();$("#playerRank").textContent=player.rank||"NOVATO";$("#playerLevel").textContent=player.level||1;$("#playerXp").textContent=xp;$("#playerXpNext").textContent=next;$("#expResource").textContent=xp;$("#crystalsResource").textContent=player.crystals||0;$("#goldResource").textContent=player.gold||0;$("#avatarMini").textContent=n.charAt(0).toUpperCase();$("#avatarLarge").textContent=n.charAt(0).toUpperCase();$("#summaryName").textContent=n.toUpperCase();$("#summaryRank").textContent=player.rank||"NOVATO";$("#playerXpBar").style.width=pct+"%";}
function getCompleted(){return missions.filter(m=>!!player[m.completedKey]).length;}
function getCurrent(){if(!player.mission1Completed)return 0;if(!player.mission2Completed)return 1;return -1;}
function openMission(index){const m=missions[index];if(!m)return;const unlocked=index===0||!!player[missions[index-1].completedKey];if(!unlocked)return;window.location.href=m.file;}
function render(){const done=getCompleted(), percent=Math.round(done/missions.length*100);$("#actProgressText").textContent=`${done} / ${missions.length}`;$("#actProgressBar").style.width=percent+"%";$("#actPercent").textContent=percent+"% completado";const current=getCurrent();$("#continueBtn").disabled=current===-1;$("#continueBtn").textContent=current===-1?"ACTO COMPLETADO ✓":"CONTINUAR ✦";$("#mapHint").textContent=current===-1?"Has completado todas las misiones disponibles de este acto.":"Tu progreso queda guardado automáticamente.";$("#missionList").innerHTML=missions.map((m,i)=>{const completed=!!player[m.completedKey], unlocked=i===0||!!player[missions[i-1].completedKey], isCurrent=i===current;let status=completed?"✓ COMPLETADA":isCurrent?"⚔ EN PROGRESO":unlocked?"🔓 DESBLOQUEADA":"🔒 BLOQUEADA";let action=completed?"REVISAR":isCurrent?"CONTINUAR":unlocked?"COMENZAR":"BLOQUEADA";return `<article class="mission-node ${completed?'completed':''} ${isCurrent?'current':''} ${!unlocked?'locked':''}"><div><div class="node-top"><span class="node-number">MISIÓN ${String(m.id).padStart(2,'0')}</span><span class="node-status">${status}</span></div><h2 class="node-title">${m.title}</h2><p class="node-desc">${m.desc}</p></div><div class="node-bottom"><span class="node-reward">RECOMPENSA · ${m.reward}</span><button class="node-action" data-index="${i}" ${!unlocked?'disabled':''}>${action} ${completed?'↺':'✦'}</button></div></article>`;}).join("");}
$("#continueBtn").onclick=()=>{const c=getCurrent();if(c>=0)openMission(c)};$("#backHome").onclick=()=>window.location.href="home.html";$("#missionList").addEventListener("click",e=>{const b=e.target.closest(".node-action");if(!b)return;openMission(Number(b.dataset.index));});updateHud();render();save();
